#!bin/bash

packages() {
  source .packages/bin/activate
  pip install -r requirements.txt
}

migrate() {
  python manage.py makemigrations
  python manage.py makemigrations thumbnail
  python manage.py migrate
  python manage.py loaddata fixtures/dev/*.yaml
}

makemessages() {
  python manage.py makemessages -l ja
  python manage.py compilemessages
}

hamlpy() {
  hamlpy-watcher . &
}

runserver() {
  echo "from helpers.score import calculate_score; calculate_score()" | python manage.py shell
  python manage.py runserver &
}

kill() {
  pkill -f 'python manage.py runserver'
  echo 'killed manage.py runserver...'
  pkill -f 'hamlpy-watcher'
  echo 'killed hamlpy-watcher...'
  echo
}

case "$1" in
  packages)
    packages
    ;;

  migrate)
    migrate
    ;;

  makemessages)
    makemessages
    ;;

  hamlpy)
    hamlpy
    ;;

  runserver)
    runserver
    ;;

  all)
    packages
    migrate
    makemessages
    hamlpy
    runserver
    ;;

  kill)
    kill
    ;;
esac
