# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('G', 'Good'), ('P', 'Pass')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(db_index=True)),
                ('good_score', models.PositiveIntegerField(db_index=True)),
                ('pass_score', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_reactions', to='reactions.Reaction')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_reactions', to='reactions.Reaction')),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_rates', to='reactions.Reaction'),
        ),
        migrations.AddField(
            model_name='rate',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_rates', to='reactions.Reaction'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('rator', 'reaction')]),
        ),
    ]
