# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_auto_20160908_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='good_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='pass_score',
        ),
    ]
