# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_auto_20161030_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='contents',
            field=models.TextField(db_index=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='score',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='スコア'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='タイトル'),
        ),
    ]
