# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reactions', '0002_auto_20161103_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ratee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_as_ratee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_as_rater', to=settings.AUTH_USER_MODEL),
        ),
    ]
