# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_auto_20161010_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='title',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
