# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_auto_20161103_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_as_ratee', to=settings.AUTH_USER_MODEL),
        ),
    ]
