# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0004_auto_20161103_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
