# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0004_reaction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_reactions', to='reactions.Reaction'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_reactions', to='reactions.Reaction'),
        ),
    ]
