# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0006_auto_20161013_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
