# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0005_auto_20161104_0459'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20161103_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RE', 'Reaction'), ('RA', 'Rating')], max_length=2)),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='active_notifications', to=settings.AUTH_USER_MODEL)),
                ('passive_user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='passive_notifications', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reactions.Rating')),
                ('reaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reactions.Reaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
