# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reactions.Rating'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reactions.Reaction'),
        ),
    ]
